language: python
python:
  - "2.6"
  - "2.7"
script:
  - "./prep.py -s test/sum/spec.json -t test/sum/sum.txt -o out"
  - "cat out"
  - "./prep.py -s test/sum/spec.json -t test/sum/sum1.txt -o out"
  - "cat out"
